language: node_js
node_js:
  - 8
  - 10

cache:
  yarn: true

# See: https://github.com/mozilla/addons-frontend/issues/3034
install: yarn install --pure-lockfile

script:
  - yarn test
  # Make sure we can build a production bundle.
  # This also does type checking.
  - yarn build

matrix:
  fast_finish: true
